#!/bin/bash

# Print a message to console
echo "Starting Prime Instinct initialization..."

# Create directories if they don't exist
mkdir -p /var/www/html/logs
mkdir -p /var/www/html/uploads
mkdir -p /var/www/html/admin/uploads

# Set proper permissions for Apache
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html/uploads
chmod -R 755 /var/www/html/admin/uploads
chmod -R 755 /var/www/html/logs

# Enable .htaccess if it exists
if [ -f /var/www/html/.htaccess ]; then
    echo "Enabling .htaccess file..."
    chmod 644 /var/www/html/.htaccess
fi

# Set the correct PHP timezone
if [ ! -z "$TIMEZONE" ]; then
    echo "Setting timezone to $TIMEZONE"
    sed -i "s|;date.timezone =|date.timezone = $TIMEZONE|g" /usr/local/etc/php/php.ini
fi

# Check if we have the database environment variables set
if [ -z "$DB_HOST" ] || [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ] || [ -z "$DB_NAME" ]; then
    echo "WARNING: Database environment variables not fully set. Please check your Coolify configuration."
fi

# Create or update .env file with environment variables
echo "# Auto-generated by coolify-init.sh" > /var/www/html/.env
echo "DB_HOST=${DB_HOST:-localhost}" >> /var/www/html/.env
echo "DB_USER=${DB_USER:-root}" >> /var/www/html/.env
echo "DB_PASSWORD=${DB_PASSWORD:-}" >> /var/www/html/.env
echo "DB_NAME=${DB_NAME:-prime}" >> /var/www/html/.env
echo "DEBUG=${DEBUG:-false}" >> /var/www/html/.env
echo "TIMEZONE=${TIMEZONE:-America/Bogota}" >> /var/www/html/.env

echo "Environment configuration completed."

# Start Apache in foreground
echo "Starting Apache web server..."
apache2-foreground
