[build]
  # This is a PHP project, so we don't have a build command
  command = "echo 'No build command needed for PHP'"
  publish = "/"

# Redirect all traffic to index.php to handle routing
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
  force = false
  conditions = {Path = {exclude = ["**.jpg", "**.jpeg", "**.png", "**.gif", "**.css", "**.js", "**.ico"]}}

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
